version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
        - ./alembic/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
volumes:
    pgdata:
        external: true