version: '3.8'

services:
  ui:
    build: ./view
    ports:
        - 3000:3000
  api:
    build: .
    ports:
        - 5000:5000
    depends_on: 
        - postgres
    command: bash -c "./wait-for-it.sh postgres:5432 && alembic upgrade head && python main.py"
  postgres:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
        - ./alembic/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
volumes:
    pgdata:
        external: true